[build]
  base = ""
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  VITE_SUPABASE_URL = "Add your Supabase URL here"
  VITE_SUPABASE_ANON_KEY = "Add your Supabase anon key here"
  REACT_APP_GEMINI_API_KEY = "AIzaSyA8hEIGPg4evHY9-cOwGrdcPV6iMxBbdNA" 